// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import { RecoveryVerifier } from "./RecoveryVerifier.sol";

contract RecoveryVerifierTest {
    bytes32 internal constant ROOT =
        0xf77bf4ca4fd705f6097cb40123adf53cbf832811fbe035acbfc90b08bd4efbbd;
    address internal constant ACCOUNT = 0x00114fB22331AF3477C43Ce79Fd43d0BD71B5Fa2;
    uint256 internal constant AMOUNT = 6_598_519_681_826_828_436;

    RecoveryVerifier internal verifier;

    function setUp() public {
        verifier = new RecoveryVerifier(ROOT);
    }

    function testValidProofFromAccumulatorReturnsTrue() public view {
        bytes32[] memory proof = _proofVector();
        require(verifier.verify(ACCOUNT, AMOUNT, proof), "valid proof should return true");
    }

    function testWrongAmountReturnsFalse() public view {
        bytes32[] memory proof = _proofVector();
        require(!verifier.verify(ACCOUNT, AMOUNT + 1, proof), "wrong amount should fail");
    }

    function testWrongAccountReturnsFalse() public view {
        bytes32[] memory proof = _proofVector();
        require(
            !verifier.verify(0x1111111111111111111111111111111111111111, AMOUNT, proof),
            "wrong account should fail"
        );
    }

    function testWrongProofReturnsFalse() public view {
        bytes32[] memory proof = _proofVector();
        proof[0] = bytes32(uint256(proof[0]) ^ 1);
        require(!verifier.verify(ACCOUNT, AMOUNT, proof), "wrong proof should fail");
    }

    function testRootImmutabilityBehavior() public view {
        bytes32 beforeRoot = verifier.merkleRoot();
        bytes32[] memory proof = _proofVector();

        verifier.verify(ACCOUNT, AMOUNT, proof);

        bytes32 afterRoot = verifier.merkleRoot();
        require(beforeRoot == ROOT, "constructor root mismatch");
        require(afterRoot == ROOT, "root changed after calls");
    }

    // Vector extracted from data/accumulator.json generated by modules/accumulator/scripts/build-accumulator.ts.
    function _proofVector() internal pure returns (bytes32[] memory proof) {
        proof = new bytes32[](10);
        proof[0] = 0xd9343b5208551bb96e91d265967e2d48b29a9ba71c1bd0f253b05581b2e9cf03;
        proof[1] = 0xf86b69a7d3117c96195aab66ccd902db9d2e0a0d62fe708122f5b6fda20c9de8;
        proof[2] = 0x832f88d7cbaa156916464ff61710b6a633b0ed09b07b21499fd452d62fe48254;
        proof[3] = 0x0bc4eb1346436fa3a6b8b464825fffdb65259f01cac7f9573222c1969e4ceb3f;
        proof[4] = 0xbf14ee571eabb1de5647d5c057fcf024262d93ffa6501fe26cc3b3f8e7018d7f;
        proof[5] = 0x4c6dd176bc0b99f1ee644a05a43d34aaa85b58b920cdb1abf3849c8c4606e94b;
        proof[6] = 0x1e6fdff944c49959c018341e4fa1460c8fd3d3ab40d2a79c929c9b0db13dc02a;
        proof[7] = 0xc71efc2a298428c1f7d4c1f37815d5bcaa0eb366844fd4ae89b11f7a1a088905;
        proof[8] = 0x16e0c706ea44490df2d39db31bfec83808316ae3e59a5e21545614f5d112ff02;
        proof[9] = 0x5e7b9f9814327b760aeef32f6c0f30a4dd238efbf5152d300baa96f3cedcbad1;
    }
}
